### PR TITLE
[160] ConnectedComponents checkpointing should construct FileSystem using Path

### LINKED ISSUE #160: ConnectedComponents checkpointing should construct FileSystem using Path
See https://www.mail-archive.com/user@spark.apache.org/msg60669.html for the original bug report.  I recommend we modify FileSystem constructors to take Path + hadoop config, rather than only the hadoop config.  That should be more robust AFAIK.

### PR DESCRIPTION
**Pull request by felixcheung**
to make sure we are using the right FileSystem.
took clue from https://github.com/apache/spark/blob/master/streaming/src/main/scala/org/apache/spark/streaming/dstream/DStreamCheckpointData.scala#L88

fix #160

### CODE REVIEW

File: src/main/scala/org/graphframes/lib/ConnectedComponents.scala [hunk 1]
```diff
@@ -336,8 +338,11 @@ object ConnectedComponents extends Logging {
 
         // remove previous checkpoint
         if (iteration > checkpointInterval) {
-          FileSystem.get(sc.hadoopConfiguration)
-            .delete(new Path(s"${checkpointDir.get}/${iteration - checkpointInterval}"), true)
+          val path = new Path(s"${checkpointDir.get}/${iteration - checkpointInterval}")
+          if (fileSystem == null) {
```
Comment (thunterdb) [inline src/main/scala/org/graphframes/lib/ConnectedComponents.scala]: how expensive is it to obtain a file system object? I suspect it is negligible compared to the cost of other Spark operations. Let's us not store it unless it is necessary.

**Comment by thunterdb** [comment]
@felixcheung thanks, I have a comment

File: src/main/scala/org/graphframes/lib/ConnectedComponents.scala (hunk 1 above)
Comment (felixcheung) [inline src/main/scala/org/graphframes/lib/ConnectedComponents.scala]: From what I can see
- DStreamCheckpointData.scala does it this way but its history is hard to track down since it is moved in 2014
- this is what the call [leads to](https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L3285) - basically it hits a lock multiple times mostly to cached the returned FileSystem

Since it is caching already let's move to not store it.

Comment (felixcheung) [inline src/main/scala/org/graphframes/lib/ConnectedComponents.scala]: although to fix #162, we will likely need to store the FileSystem in order to clean up the very last checkpoint saved.

but more can come then

**Comment by thunterdb** [comment]
One of the tests ran out of heap space. We should be able to fix that in `python/run-tests.sh` with something like that:
http://stackoverflow.com/questions/31464727/increase-memory-available-to-pyspark-at-runtime

**Comment by felixcheung** [comment]
all passed

**Comment by jkbradley** [comment]
LGTM, thank you!
